### ISSUE TITLE
Feature previews

### ISSUE THREAD

**Issue by toddmohney** [gust/feature-creature#14]
So that I can find and view the details of a specific feature or scenario
I want to see the feature and scenario titles within each file in the list view

Within the feature file listing view and
below each feature file:
- show the feature title
- show each scenario title

Example screenshot of file listing view:
![screen shot 2015-10-17 at 12 40 25 pm](https://cloud.githubusercontent.com/assets/400775/10560089/21e30ed6-74ce-11e5-826f-7d0453696db5.png)

**Comment by pdswan** [comment]
Might be interesting to pull the feature title line here when it exists and
fall back to the file name when it doesn't. Probably a second pass concern
though.

**Comment by toddmohney** [comment]
This seems pretty unnecessary at this point. I'm gonna close this issue.
Let's let a better solution arise as we flesh out our UI
