### ISSUE TITLE
Get/Create user role

### ISSUE THREAD

**Issue by toddmohney** [gust/feature-creature#37]
Add API endpoints for creating and retrieving a User Role

**Comment by zephyr-dev** [comment]
No weekends off for you huh.

**Comment by GustNash** [comment]
Mystery zephyr man

On Sun, Nov 15, 2015 at 7:21 AM -0800, "zephyr-dev" notifications@github.com wrote:

No weekends off for you huh.

**Comment by toddmohney** [comment]
I'm having such a good time. I've got records playing, breakfast in my belly, and teh codez are shaping up nicely! Haskell and Elm are becoming pretty good friends of mine.
