### ISSUE TITLE
Importing existing feature files

### ISSUE THREAD

**Issue by toddmohney** [gust/feature-creature#8]
Feature: Importing existing feature files
  As a product contributor
  So that I can manage my product's features
  I want to import my existing feature descriptions

Possibilities
- Import from git repo (store url, fetch repo, find feature files)
- Import from zip 
- Something else?

**Comment by pdswan** [comment]
I think import from repo is a good start, but it brings up #11

**Comment by jvans1** [comment]
Agree I think start from repo. zip file isn't necessary for an mvp. The importing should be a good little project to use parsers for
